#!/usr/bin/env bash
set -euo pipefail

# where this script lives
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# one level up is your project root
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

OUT_FILE="${1:-$SCRIPT_DIR/AutoGeneratedPostDeploy.sql}"
TARGET_DIR="$(dirname "$OUT_FILE")"

mkdir -p "$TARGET_DIR"

cat <<'EOF' > "$OUT_FILE"
-- This file is auto-generated by running generate-postdeploy.sh; do NOT hand-edit
EOF

find "$ROOT_DIR/Tests" -type f -name '*.sql' | sort \
  | while IFS= read -r file; do
      rel="${file#"$ROOT_DIR/Tests"/}"
      echo ":r ../Tests/$rel" >> "$OUT_FILE"
  done

echo "✅  Wrote $OUT_FILE"
