<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Azure.Storage.Blobs" />
        <PackageReference Include="Microsoft.Extensions.Azure" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Exporter.Zipkin" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" />
        <PackageReference Include="Serilog.Extensions.Hosting" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
    </ItemGroup>
    <ItemGroup>
        <Compile Include="..\Bookings\Infrastructure\Logging.cs">
            <Link>Infrastructure\Logging.cs</Link>
        </Compile>
        <Compile Include="..\Bookings\Infrastructure\Telemetry.cs">
            <Link>Infrastructure\Telemetry.cs</Link>
        </Compile>
        <Compile Include="..\..\kurrentdb\Bookings.Payments\Domain\*.cs">
            <Link>Domain\%(Filename)%(Extension)</Link>
        </Compile>
        <Compile Include="..\..\kurrentdb\Bookings.Payments\Application\*.cs">
            <Link>Application\%(Filename)%(Extension)</Link>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="$(SrcRoot)\Extensions\src\Eventuous.Extensions.AspNetCore\Eventuous.Extensions.AspNetCore.csproj"/>
        <ProjectReference Include="$(SrcRoot)\Extensions\src\Eventuous.Extensions.DependencyInjection\Eventuous.Extensions.DependencyInjection.csproj"/>
        <ProjectReference Include="$(SrcRoot)\Diagnostics\src\Eventuous.Diagnostics.OpenTelemetry\Eventuous.Diagnostics.OpenTelemetry.csproj"/>
        <ProjectReference Include="$(SrcRoot)\Gateway\src\Eventuous.Gateway\Eventuous.Gateway.csproj"/>
        <ProjectReference Include="$(SrcRoot)\Core\gen\Eventuous.Subscriptions.Generators\Eventuous.Subscriptions.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="$(SrcRoot)\Core\gen\Eventuous.Shared.Generators\Eventuous.Shared.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="$(SrcRoot)\Experimental\src\Eventuous.Spyglass\Eventuous.Spyglass.csproj"/>
        <ProjectReference Include="$(SrcRoot)\Experimental\gen\Eventuous.Spyglass.Generators\Eventuous.Spyglass.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="$(SrcRoot)\SqlServer\src\Eventuous.SqlServer\Eventuous.SqlServer.csproj" />
        <ProjectReference Include="$(SrcRoot)\Azure\src\Eventuous.Azure.ServiceBus\Eventuous.Azure.ServiceBus.csproj" />
    </ItemGroup>
</Project>