services:

  kurrentdb:
    container_name: esdemo-kurrentdb
    # On Apple Silicon, use kurrentplatform/kurrentdb:26.1.1-experimental-arm64-10.0-noble
    image: kurrentplatform/kurrentdb:26.1.1
    command: --insecure --run-projections=All --enable-atom-pub-over-http
    ports:
      - '2113:2113'

  azurite:
    container_name: esdemo-azurite
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite-blob --blobHost 0.0.0.0 --skipApiVersionCheck
    ports:
      - '10000:10000'

  mongo:
    container_name: esdemo-mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  zipkin:
    image: openzipkin/zipkin
    container_name: esdemo-zipkin
    ports:
      - "9411:9411"

  prometheus:
    container_name: esdemo-prometheus
    image: prom/prometheus:v2.17.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: esdemo-grafana
    image: grafana/grafana:6.7.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./grafana/dashboards:/dashboards

  seq:
    image: datalust/seq:latest
    container_name: esdemo-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

networks:
  default:
    name: eventuous-demo
