version: '3.7'

services:
  rabbitmq:
    container_name: eventuous-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
