name: PR Build and test
on:
  workflow_dispatch:
  pull_request:

jobs:
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
  test:
    runs-on: ubuntu-latest
#    env:
#      TC_CLOUD_TOKEN: ${{ secrets.TC_TOKEN }}
    steps:
      -  
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'
      -  
        name: Install dependencies
        run: dotnet restore
      -  
        name: Build
        run: dotnet build --configuration Debug --no-restore
      -  
        name: Prepare Testcontainers Cloud agent
        if: env.TC_CLOUD_TOKEN != ''
        uses: atomicjar/testcontainers-cloud-setup-action@main
      -  
        name: Run tests
        run: dotnet test --no-build
      -  
        name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: |
            test-results/*.xml