name: Build and test PRs with docs

on:
  pull_request:
    paths: 
      - docs/**

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      -  
        name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: docs/package.json
      -  
        name: Checkout
        uses: actions/checkout@v4
      -  
        name: Build docs
        run: |
          cd docs
          pnpm install
          pnpm build
