name: Build and test PRs with docs

on:
  pull_request:
    paths: 
      - docs/**

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      -  
        name: Checkout
        uses: actions/checkout@v4
      -  
        name: Build docs
        run: |
          cd docs
          yarn install
          yarn build
